import {Column} from '../technical/orm/column.decorator';
import {SQLiteType} from '../technical/orm/sqlite-type';
import {Entity} from '../technical/orm/entity.decorator';


@Entity('motif')
export class MotifEntity {

    @Column({name: 'id', type: SQLiteType.INTEGER, comment: 'Id du motif', primary: true, autoGenerated: true})
    id: number;

    @Column({
        name: 'code',
        type: SQLiteType.TEXT,
        comment: 'Code du motif de non distribution',
        notNull: true
    })
    codeBarre: string;

    @Column({
        name: 'libelle',
        type: SQLiteType.TEXT,
        comment: 'Libelle du motif de non distribution',
        notNull: true
    })
    libelle: string;
}
