version: 2
jobs: 
  deploy:
    docker: 
      - image: circleci/android:api-29-node
    steps:
      - checkout
      - run:
          name: "Deploy to store"
          command: |
            apt-get install jq
            apt-get install openssl
            apt-get install curl
            apt-get install sed
            chmod +x .circleci/upload-playstore.sh
            .circleci/upload-playstore.sh /tmp/apk/jp-mobile-1.apk 2 internal false
  build: 
    docker: 
      - image: circleci/android:api-29-node
    working_directory: ~/repo
    environment: 
      JVM_OPTS: -Xmx3200m
    steps: 
      - checkout
      - run:
          name: "Delete useless artifacts"
          command: |
            echo 'Suppression des APK'
            unlink jp-mobile.apk || true
            unlink app-release-unsigned.apk || true
      - run:
          name: "Install gradle"
          command: |
            wget https://services.gradle.org/distributions/gradle-5.4.1-bin.zip -P /tmp
            sudo unzip -d /opt/gradle /tmp/gradle-*.zip
            echo 'export GRADLE_HOME=/opt/gradle/gradle-5.4.1' >> $BASH_ENV
            echo 'export PATH=$PATH:/opt/gradle/gradle-5.4.1/bin' >> $BASH_ENV
            source $BASH_ENV
      - run: 
          name: "Install ionic and cordova"
          command: |
            sudo npm install -g ionic cordova yarn
      - run: 
          name: "Install npm packages"
          command: |
            yarn install
      - run: 
          name: "Install Cordova plugins and add android platform"
          command: |
            ionic cordova platform add android --noresources
            ionic config set -g telemetry true
      - run:
          name: "Increment version"
          command: |
            export NEW_VERSION=$(gradle -q incrementMinorVersion | tail -n 1)
      - run: 
          name: "Generate apk"
          command: |
            ionic cordova build android --release --prod
            mkdir -p /tmp/apk
            cp -r platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk /tmp/apk
      - run:
          name: "Sign the APK"
          command: |
            yes ${KEYSTORE_PASSWORD} | jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore sido-mobile-keystore.jks /tmp/apk/app-release-unsigned.apk ${KEYSTORE_ALIAS} || true
      - run:
          name: "ZipAlign the APK"
          command: |
            ${ANDROID_HOME}/build-tools/29.0.1/zipalign -v 4 /tmp/apk/app-release-unsigned.apk jp-mobile-1.apk || true
      - run:
          name: "Copy signed APK to directory"
          command: |            
            cp -r jp-mobile-1.apk /tmp/apk
      - store_artifacts: 
          path: /tmp/apk
          destination: apks

workflows: 
  version: 2
  only_deploy: 
    jobs:
      - build
      - deploy:
          requires:
            - build
          context: env
