version: 2
jobs: 
  deploy:
    docker: 
      - image: olivejp/android-deploy:1.0.6
    steps:
      - checkout
      - run:
          name: "Deploy to store"
          command: |
            # wget "https://$CIRCLE_PREVIOUS_BUILD_NUM-199160063-gh.circle-artifacts.com/0/apks/app-release-unsigned.apk"
            wget "https://112-199160063-gh.circle-artifacts.com/0/apks/app-release-unsigned.apk"
            sh /home/circleci/deploy.sh "${GOOGLE_KEY}" app-release-unsigned.apk 2 internal false ${KEYSTORE_PASSWORD} sido-mobile-keystore.jks ${KEYSTORE_ALIAS}
  build: 
    docker: 
      - image: circleci/android:api-29-node
    working_directory: ~/repo
    environment: 
      JVM_OPTS: -Xmx3200m
    steps: 
      - checkout
      - run:
          name: "Install gradle"
          command: |
            wget https://services.gradle.org/distributions/gradle-5.4.1-bin.zip -P /tmp
            sudo unzip -d /opt/gradle /tmp/gradle-*.zip
            echo 'export GRADLE_HOME=/opt/gradle/gradle-5.4.1' >> $BASH_ENV
            echo 'export PATH=$PATH:/opt/gradle/gradle-5.4.1/bin' >> $BASH_ENV
            source $BASH_ENV
      - run: 
          name: "Install ionic and cordova"
          command: |
            sudo npm install -g ionic cordova yarn
      - run: 
          name: "Install npm packages"
          command: |
            yarn install
      - run: 
          name: "Install Cordova plugins and add android platform"
          command: |
            ionic cordova platform add android --noresources
            ionic config set -g telemetry true
      - run: 
          name: "Generate apk"
          command: |
            ionic cordova build android --release --prod
            mkdir -p /tmp/apk
            cp -r platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk /tmp/apk
      - store_artifacts: 
          path: /tmp/apk
          destination: apks

workflows: 
  version: 2
  only_deploy: 
    jobs:
      # - build:
      #     context: env
      - deploy:
          # requires:
          #   - build
          context: env
