version: 2
jobs: 
  deploy:
    docker: 
      - image: olivejp/android-deploy:1.0.2
    steps:
      - checkout
      - run:
          name: "Deploy to store"
          command: |
            wget "https://$CIRCLE_PREVIOUS_BUILD_NUM-199160063-gh.circle-artifacts.com/0/apks/app-release-unsigned.apk"
            sh deploy.sh $GOOGLE_KEY app-release-unsigned.apk 2 internal false $KEYSTORE_PASSWORD sido-mobile-keystore.jks $KEYSTORE_ALIAS
  build: 
    docker: 
      - image: circleci/android:api-29-node
    working_directory: ~/repo
    environment: 
      JVM_OPTS: -Xmx3200m
    steps: 
      - checkout
      - run:
          name: "Install gradle"
          command: |
            wget https://services.gradle.org/distributions/gradle-5.4.1-bin.zip -P /tmp
            sudo unzip -d /opt/gradle /tmp/gradle-*.zip
            echo 'export GRADLE_HOME=/opt/gradle/gradle-5.4.1' >> $BASH_ENV
            echo 'export PATH=$PATH:/opt/gradle/gradle-5.4.1/bin' >> $BASH_ENV
            source $BASH_ENV
      - run: 
          name: "Install ionic and cordova"
          command: |
            sudo npm install -g ionic cordova yarn
      - run: 
          name: "Install npm packages"
          command: |
            yarn install
      - run: 
          name: "Install Cordova plugins and add android platform"
          command: |
            ionic cordova platform add android --noresources
            ionic config set -g telemetry true
      - run: 
          name: "Generate apk"
          command: |
            ionic cordova build android --release --prod
            mkdir -p /tmp/apk
            cp -r platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk /tmp/apk
      # - run:
      #     name: "Sign the APK"
      #     command: |
      #       yes $KEYSTORE_PASSWORD | jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore sido-mobile-keystore.jks /tmp/apk/app-release-unsigned.apk $KEYSTORE_ALIAS || true
      # - run:
      #     name: "ZipAlign the APK"
      #     command: |
      #       $ANDROID_HOME/build-tools/29.0.1/zipalign -v 4 /tmp/apk/app-release-unsigned.apk jp-mobile.apk || true
      # - run:
      #     name: "Copy signed APK to directory"
      #     command: |            
      #       cp -r jp-mobile.apk /tmp/apk
      - store_artifacts: 
          path: /tmp/apk
          destination: apks

workflows: 
  version: 2
  only_deploy: 
    jobs:
      - build:
          context: env
      - deploy:
          requires:
            - build
          context: env
