version: 2
jobs: 
  deploy:
    docker: 
      - image: stedolan/jq
    environment:
      GOOGLE_KEY: '{  "type": "service_account",  "project_id": "api-6509887218928901077-258039",  "private_key_id": "bcc2e78c5dd694bb115eb52d50ef9d482fdc3639",  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDqRk58hqdHFf40\ntBxDXBRT646PyWnNVoyO4G6RXEQd8IQ9DAMINzD1HTSZdlEtcqimwLCE6qM0MJY5\nIF8+Jr80xryPe9I224C1uTnJUldoRhLTyHW+0K9QlPpSitg9aNaum1kqCEY9EGk1\ny3Bb2hhjV5lqbQVPGHG5drt/wyeBL0CPUBL1+zK9MRISn2vUHv2m7oRzFDtODXsk\naLyn+UlocpM4WlWV1LMw7ODk4xbaj7ktEDJG5dUwlfdgKzcQLPhFTsXKFGZU9Td8\nQyZPUZo6ur7tSJPKhEskfNAOMkdFn8V7U+D40IqEYXWUe8DaWK2f31zIxyDfOKxN\nW3qfnRFLAgMBAAECggEAGnYvhlRFT7u1t2lCqf8cErCQLUCQUU+916OVCZk03nbc\n0PJq40IspvsSBmV9XNdPImqwZYsFPS9hwHkeGOySe1kZUlGnmGepvZz64HkLA22q\n0b4aQp/atYzmS22AaEtPuHA2nY9Ks7oHUDq26cEUMSBjZUiEKX921P6Kxi8aZrZi\nzq7ZHseZFMRJMo+4BhgWRCQvzVhKrcm10mfo8ZrIg/CQ3q0APqXFdvSjksIHo2Cw\ndHdMnNOBhojIC3x/VQkar+hU1NSoS0RgGTbvkcSawMFTCv5OoANc0lt13ogOC/hq\nSMZzB+GDslflRE2gpd+tPADhJf0vjMFlas5TfJFb/QKBgQD2sqjMi5uvDPtzg61g\n4cLl5y7rKepFDHvWaQOgdGt52D1pXoN3IA8LbOVcq0GIW4iodjhvozH2oxwYuFRi\nCG8rbULDJP/9QMlFG7pmaR/siNnEgr9IeaiBOBhdr/h5XrsLWJWBYaI4C6z5P5kk\nPHEmgniquSDpLMIfH2F/zXQ/dQKBgQDzG7oucfTdkvCKjrTPjpn71SyWub7OU9Cz\nna4jHhHyrK8TJ/vgHWmFx7nk57w0027jlAJP1k+DzkGrdrIGYQCJmNiTyKGgHr+I\ntLUyNLnQOxEJwo4UcGGc8NOWoOd+iIScxKuITO4MEMwnY5qYNRthkaFgo+UJPKzx\nxjgmVHS1vwKBgQDoSc+xUh9Uk8fMvAcr+0f2DFncaopBXADbIeSdWCG/CALDTZBC\nQfiIjI/nUwYQrAeggDihvauVDX6uNBqYeFKdNHMxpow33aHmpbY9Ke06Xp2WcHpG\ndu9YRQaEaOZw+ebrRwz3V4RUe4Hy65R6T0NHvIB8WHcJt/BNN9Ipcb5s5QKBgDlC\ncpu144K8tUMtUZEBeWtDTnlBzpsySpnDrdw/nOKXobTVWhHzW4NTA4nSuxWGJzwb\nBGBhjeDxl64XCt9NwZ6nDXvhaZAZLeu5BGSK3qkZAG5YELbnsVYRswRraZr39KQn\n/m7gD8Fvw2YTo7nt6EEW1/e3Ip8GV4Wqtlbw1XxpAoGBAOUcs7MAQrgj5Mm2wNEm\nkT4z0ZoP/QoTPTNa5U9FCjxn3vjj3RHETF9H6GXaZJoDL9svLDRSdHYOLWLKaxJq\nyx32nZEoKpSQ4sfluC+uXDTuyeqWJJ20W9ZCwwyvvq098vSGPM10r1AAF1pFhO+b\n2UNtkhGMbFUF0BF9wZbAo7U9\n-----END PRIVATE KEY-----\n",  "client_email": "bitrise-deploy@api-6509887218928901077-258039.iam.gserviceaccount.com",  "client_id": "103574490951992945778",  "auth_uri": "https://accounts.google.com/o/oauth2/auth",  "token_uri": "https://oauth2.googleapis.com/token",  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/bitrise-deploy%40api-6509887218928901077-258039.iam.gserviceaccount.com"}'
    steps:
      - checkout
      - run:
          name: "Deploy to store"
          command: |
            echo ${GOOGLE_KEY}
            chmod +x .circleci/upload-playstore.sh
            .circleci/upload-playstore.sh ${GOOGLE_KEY} ./jp-mobile.apk 1 internal false
  build: 
    docker: 
      - image: circleci/android:api-29-node
    working_directory: ~/repo
    environment: 
      JVM_OPTS: -Xmx3200m
    steps: 
      - checkout
      - run:
          name: "Delete artifactory"
          command: |
            echo 'Suppression de l APK'
            unlink jp-mobile.apk || true
      - run: 
          name: "Install gradle"
          command: |
            wget https://services.gradle.org/distributions/gradle-5.4.1-bin.zip -P /tmp
            sudo unzip -d /opt/gradle /tmp/gradle-*.zip
            echo 'export GRADLE_HOME=/opt/gradle/gradle-5.4.1' >> $BASH_ENV
            echo 'export PATH=$PATH:/opt/gradle/gradle-5.4.1/bin' >> $BASH_ENV
            source $BASH_ENV
      - run: 
          name: "Install ionic and cordova"
          command: |
            sudo npm install -g ionic cordova yarn
      - run: 
          name: "Install npm packages"
          command: |
            yarn install
      - run: 
          name: "Install Cordova plugins and add android platform"
          command: |
            ionic cordova platform add android --noresources
            ionic config set -g telemetry true
      - run: 
          name: "Generate apk"
          command: |
            ionic cordova build android --release --prod
            mkdir -p /tmp/apk
            cp -r platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk /tmp/apk
      - run:
          name: "Sign the APK"
          command: |
            yes password | jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore sido-mobile-keystore.jks /tmp/apk/app-release-unsigned.apk sido-mobile-keystore || true
      - run:
          name: "ZipAlign the APK"
          command: |
            ${ANDROID_HOME}/build-tools/29.0.1/zipalign -v 4 app-release-unsigned.apk jp-mobile.apk || true
      - run:
          name: "Copy signed APK to directory"
          command: |            
            cp -r jp-mobile.apk /tmp/apk
      - store_artifacts: 
          path: /tmp/apk
          destination: apks

workflows: 
  version: 2
  only_deploy: 
    jobs: 
      - deploy