import {SQLiteType} from './sqlite-type';

export class ColumnDefinition {
    name: string;               // Nom de la colonne en base
    type: SQLiteType;           // Type de la colonne
    primary?: boolean;          // true si c'est une clé primaire, false sinon
    length?: number;            // Longeur de la colonne en base
    comment?: string;           // Commentaire sur la colonne (non utilisée pour le moment)
    autoGenerated?: boolean;    // Dans le cas d'une clé primaire on précise si elle est auto générée
    notNull?: boolean;          // true, si la colonne ne doit pas être nulle, false sinon
    unique?: boolean;           // true, si la valeur de cette colonne doit être unique, false sinon
}
