import {SQLiteType} from './sqlite-type';

export class ColumnDefinition {
    name: string;
    type: SQLiteType;
    primary?: boolean;
    length?: number;
    comment?: string;
    autoGenerated?: boolean;
    notNull?: boolean;
    unique?: boolean;
}
